### PR TITLE
Add Apigee Kickstart, a Radix subtheme

### PR DESCRIPTION
**Pull request by jacine**

### CODE REVIEW

**Comment by Jaesin** [comment]
I noticed the logo is an SVG with only an embedded PNG in it. Can we just use a PNG or should we ask for a vector logo?

Everything else looks fine to me. The setup for this theme is waiting on some installation issues. You must enable the components module when installing or you will get a WSOD. 

This might help <https://www.drupal.org/node/2937955> but we would have to see which version of Drupal this is shipped with.

**Comment by Jaesin** [comment]
There is one more thing, the name Apigee 8 could be more specific. The major version may not be important and could be D9 compatible without a major rewrite (maybe?) so having it be more specific to what it provides might be better. Maybe 'Apigee Devportal Radix' or something.

**Comment by jacine** [comment]
> I noticed the logo is an SVG with only an embedded PNG in it. Can we just use a PNG or should we ask for a vector logo?

We will get a real SVG logo. The logo here belongs to Radix.  It was just generated by the Drush command. 

> This might help https://www.drupal.org/node/2937955 but we would have to see which version of Drupal this is shipped with.

I didn't realize this had landed.  Thanks, I'll see if it works.

**Comment by Jaesin** [comment]
Theme dependencies on module hasn't landed yet. The change record noted above is just a draft.

**Comment by Jaesin** [comment]
Here is a link to the Apigee logo. If it's temporary, it might be nicer to have a 1.5k vector than a 51k binary in the repo.

<https://upload.wikimedia.org/wikipedia/commons/a/aa/Apigee_logo.svg>
apigee_logo

**Comment by jacine** [comment]
@Jaesin Theme has been renamed.  I added the Favicon. The logo, however, does not look better.  I will handle this soon, just not now.

Screen Shot 2019-03-11 at 11 47 30 PM

**Review by Jaesin — APPROVED** [review]
The logo and screenshot will be addressed in followups.

Install the components module before enabling the theme for trying this out. Blocks won't be configured yet so adjust your expectations accordingly. =)

**Review by shadcn — APPROVED** [review]
Let's see if I can approve this.

**Pull request merged**
