### PR TITLE
Rebase 8.x 1.x monetization

### PR DESCRIPTION
**Pull request by jacine**

### CODE REVIEW

**Review by cnovak — APPROVED** [review]
Assuming this is all just a rebase, no new code

**Comment by jacine** [comment]
> Assuming this is all just a rebase, no new code

Yes! Thank you. :)

There were a bunch of conflicts in `.install` and `.profile`, which I believe I have resolved properly, as everything appears to be working properly in my testing.  I'd just like @arshad to take a quick look to confirm before merging when he gets a chance.

**Review by shadcn — APPROVED** [review]
Tested this. Looks good. 👍

**Comment by jacine** [comment]
Thank you!!

**Pull request merged**
