### PR TITLE
[#270] Show the username on the user profile page

### LINKED ISSUE #270: Kickstart profile hides actual username, hard to connect to REST API
## Description
The current release 1.5.0 hides the username from the system, and must autogenerate it in the background.  This makes it very hard to use the [Expose REST APIs to interact with API Docs](https://www.drupal.org/docs/8/modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs#comment-13282168) instructions since the `basic_auth` module uses the username to authenticate.  The username is hidden in the edit user form and shown in the view user profile incorrectly (displays **First Name** **Last Name**)

## To Reproduce
1. Create a new user with **First Name** "Test", **Last Name** "User", **Email** test@example.com".
2. View the user's profile page, the username will be 
user-view

### Option A: Username and password can be used 
1. The username would be properly displayed
2. The username would be chosen during registration
3. The user could use username or password to log in

### Option B: Username is not used in system
1. The system does not depend anywhere on username.

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #270 

This displays the username on the user profile page, enables the username field on the user forms and allows login using the email or the username.

username-on-profile

username-field

login-username-email

### CODE REVIEW

**Review by kscheirer — APPROVED** [review]
Did you mean to include the change to email_registration? Seems like a good change. This PR works for me.

@cnovak would it be worth documenting which name you're seeing at various spots in the portal? Some places it will be the _alter()ed name (ie first+last fields), in others it may still be the account name.

In rare cases, the account name can contain PII, if email address is used for ex. Depends on site configuration. This could happen when using SAML SSO for example, and mapping email address to the account name field.

**Review by cnovak — CHANGES_REQUESTED** [review]
The [Username field in user list (or anywhere) should not display "First Name" "Last Name"]( https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/270#issuecomment-540690858).

**Comment by cnovak** [comment]
Added issue https://github.com/apigee/apigee-edge-drupal/issues/280 to fix this in the Apigee Edge module.  This PR can be modified or closed if needed to remove any workarounds done in Kickstart module.

**Comment by minnur** [comment]
We still need this PR. I just moved some routine from the Apigee Edge module that automatically replaces username with Firstname and Lastname values.

See https://github.com/apigee/apigee-edge-drupal/pull/281

**Comment by minnur** [comment]
@googlebot I consent.

**Review by arlina-espinoza — APPROVED** [review]
This looks good and can be merged. Although we should follow up after https://github.com/apigee/apigee-edge-drupal/pull/281#pullrequestreview-304117418 - if `apigee_edge_user_format_name_alter()` gets removed from `apigee_edge`, then we need to make sure that the `display_name` extra field uses the _First Last_ format.

**Comment by minnur** [comment]
I think we might need that hook @arlina-espinoza it is replicates current developers list on the Apigee site

**Review by cnovak — APPROVED** [review]
This looks good to me, but would like someone to review the last commit I added to this PR to make sure the `Name` label does not change after https://github.com/apigee/apigee-edge-drupal/pull/359 goes in.  @arlina-espinoza this is something you pointed out.

**Comment by shadcn** [comment]
@cnovak I tested with the https://github.com/apigee/apigee-edge-drupal/pull/359 and this looks good. Username is displayed in the admin but first name and last name used for full name.

LGTM

admin___Apigee

**Pull request merged**
