### PR TITLE
[#311] Compress demo images

### LINKED ISSUE #311: Reduce the size of the default images for the content created during install process
The images used on the content created during the install process are huge.
We should reduce the size of these files. 

nasa-89116-unsplash.jpg is 6 MB

These sizes are causing the image styles to fail at times, especially on local machine which has memory_limit set to 128M

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #311 and #316

### CODE REVIEW

**Comment by giteshk** [comment]
Anyway we could compress these a little bit further ?

These sizes are causing the image styles to fail at times, especially on local machine which has memory_limit set to 128M

**Comment by shadcn** [comment]
@giteshk I think we could reduce the size a bit more. These are demo images so I assume they don't really need to look super sharp.

**Review by cnovak — CHANGES_REQUESTED** [review]
Can we get details on this error happening before we reduce image sizes? @arlina-espinoza said she has ran using 128M max memory and did not see issues.

**Comment by cnovak** [comment]
Our goal is to have a fast site, but of course still look good on monitors and mobile devices.  We should test to make sure everything looks good on different devices before committing this in.

Here are my notes on these images:

### [chuttersnap-255216-unsplash.png](https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/315/files#diff-16ef34a41626b0fb70a075b043c7585b)
Is now the same size, but a lower quality image which makes sense since it is a background image and looks the same.

### [aditya-vyas-1392552-unsplash.jpg](https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/315/files?short_path=15ba9b3#diff-15ba9b3dafe0bde037b762b8d1d20ab5)
Rresized down to 3184px | H: 2123px. This image needs to stay large because it scales large on the front page:
aditva-frontpage-large
That image has a width of 2545 in that screenshot above. If we did not allow it to expand to edge of viewport we could make it smaller, but the way it works now it seems we need it that large. Is it OK to scale it down on retina displays?

### [donald-giannatti-671274-unsplash.jpg](https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/315/files?short_path=f2dc13b#diff-f2dc13b644675e21ede7c65d2c081982)
This image stayed the same size of 4928px | H: 3280px , but quality is lower which is a little noticeable. Is there a reason this image was kept in such a large format? The image's largest location I believe is on a blog node and seems to have the max width of 730px on that location which I believe is the largest size used. If so can we make the image size smaller or do we need to worry about retina displays?

### [nasa-43567-unsplash.jpg](https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/315/files#diff-4f7d3f6faa90cb2c7a7adff12a1ab2cb)
This image was scaled down to W: 2928px | H: 1949px . The largest size I believe is on the blog page and used in same places as **donald-giannatti-671274-unsplash.jpg**. Why was this one scaled down and  **donald-giannatti-671274-unsplash.jpg** was not? Same thing on this one too, can it be sized smaller due to where it is being used, or will we have bad quality on retina displays?

### [nasa-43569-unsplash.jpg](https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/315/files#diff-d7bde6e0e7fdf7c22ee2a5e57fe40348)
This one is scaled down to W: 2928px | H: 1949px so same notes as **nasa-43567-unsplash.jpg**

### [nasa-89116-unsplash.jpg](https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/315/files?short_path=49c05b0#diff-49c05b0c987777b15f68990ba098c867)
This one is scaled down to W: 3000px | H: 1826px, so same notes as **nasa-43567-unsplash.jpg**

### [spacex-1130896-unsplash.jpg](https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/315/files?short_path=321d13e#diff-321d13e1645de285c21045f00b0ee07a)
This one is scaled down to W: 3000px | H: 1826px, so same notes as **nasa-43567-unsplash.jpg**

### [spacex-81773-unsplash.jpg]()
This one is scaled down to W: 3000px | H: 1826px, so same notes as **nasa-43567-unsplash.jpg**

### [terence-burke-1417892-unsplash.jpg]()
This one is scaled down to W: 3000px | H: 1826px, so same notes as **nasa-43567-unsplash.jpg**

**Comment by cnovak** [comment]
@arshad I disagree about this, we want to make sure we don't have bad quality images when showing demos. The size differences in this commit are huge already.
> @giteshk I think we could reduce the size a bit more. These are demo images so I assume they don't really need to look super sharp.

**Comment by giteshk** [comment]
Thank you for looking into this.

**Comment by shadcn** [comment]
@cnovak Thanks for testing this. I'll make the changes. I tried to reduce the size of the images depending on where they are being used. I'm testing on a non-retina, retina and a 4k screen.

**Comment by cnovak** [comment]
@arshad , make sure to check out these notes https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/317#issuecomment-583201184

**Comment by shadcn** [comment]
OK let's apply some automation to this. I created a quick script to crawl the pages, trigger the responsive breakpoints, wait for the images to generate and log the sizes.

## Pages
This is the list of pages crawled (limited to pages with images only)

|    | path                                                       |
|---:|:------------------------------------------------------------|
|  0 | /apis                                                       |
|  1 | /blog                                                       |
|  2 | /home                                                       |
|  3 | /get-started                                                |
|  4 | /article/pretium-viverra-suspendisse-potenti-fermentum-0    |
|  5 | /article/pretium-viverra-suspendisse-potenti-fermentum      |
|  6 | /article/pretium-viverra-suspendisse-potenti-1              |
|  7 | /article/pretium-viverra-suspendisse-potenti-0              |
|  8 | /article/pretium-viverra-suspendisse-potenti                |
|  9 | /article/eum-incassum-neo-refoveo-saepius-saluto-sudo-valde |

## Images with sizes
This table list all images used and the different sizes they are used at. (Breakpoints taken from https://gist.github.com/jacine/cb11830d71f93f3c4d178eddc2cf4ab8).

|    | name                                 |   width |   height |
|---:|:-------------------------------------|--------:|---------:|
|  0 | aditya-vyas-1392552-unsplash.jpg     |     991 |      566 |
|  1 | aditya-vyas-1392552-unsplash.jpg     |    1280 |      960 |
|  2 | aditya-vyas-1392552-unsplash.jpg     |     500 |      400 |
|  3 | aditya-vyas-1392552-unsplash.jpg     |    1460 |      834 |
|  4 | aditya-vyas-1392552-unsplash.jpg     |     991 |      566 |
|  5 | aditya-vyas-1392552-unsplash.jpg     |     640 |      366 |
|  6 | aditya-vyas-1392552-unsplash.jpg     |     100 |       67 |
|  7 | aditya-vyas-1392552-unsplash.jpg     |    1982 |     1133 |
|  8 | aditya-vyas-1392552-unsplash.jpg     |    3184 |     2123 |
|  9 | chuttersnap-255216-unsplash.png      |    1300 |      400 |
| 10 | chuttersnap-255216-unsplash.png      |     100 |       31 |
| 11 | chuttersnap-255216-unsplash.png      |    2600 |      800 |
| 12 | donald-giannatti-671274-unsplash.jpg |     991 |      566 |
| 13 | donald-giannatti-671274-unsplash.jpg |     500 |      400 |
| 14 | donald-giannatti-671274-unsplash.jpg |    1460 |      834 |
| 15 | donald-giannatti-671274-unsplash.jpg |     640 |      366 |
| 16 | donald-giannatti-671274-unsplash.jpg |     100 |       67 |
| 17 | donald-giannatti-671274-unsplash.jpg |    1982 |     1133 |
| 18 | nasa-43567-unsplash.jpg              |    1982 |     1133 |
| 19 | nasa-43567-unsplash.jpg              |    1460 |      834 |
| 20 | nasa-43567-unsplash.jpg              |     100 |       67 |
| 21 | nasa-43567-unsplash.jpg              |     991 |      566 |
| 22 | nasa-43567-unsplash.jpg              |     640 |      366 |
| 23 | nasa-43569-unsplash.jpg              |     500 |      400 |
| 24 | nasa-43569-unsplash.jpg              |    1982 |     1133 |
| 25 | nasa-43569-unsplash.jpg              |     640 |      366 |
| 26 | nasa-43569-unsplash.jpg              |    1460 |      834 |
| 27 | nasa-43569-unsplash.jpg              |     100 |       67 |
| 28 | nasa-43569-unsplash.jpg              |     991 |      566 |
| 29 | nasa-89116-unsplash.jpg              |     991 |      566 |
| 30 | nasa-89116-unsplash.jpg              |     500 |      400 |
| 31 | nasa-89116-unsplash.jpg              |     100 |       61 |
| 32 | nasa-89116-unsplash.jpg              |    1982 |     1133 |
| 33 | nasa-89116-unsplash.jpg              |     640 |      366 |
| 34 | profile-default.jpg                  |      80 |       80 |
| 35 | profile-default.jpg                  |     100 |      100 |
| 36 | profile-default.jpg                  |      48 |       48 |
| 37 | spacex-1130896-unsplash.jpg          |     100 |       67 |
| 38 | spacex-81773-unsplash.jpg            |     640 |      366 |
| 39 | spacex-81773-unsplash.jpg            |    1460 |      834 |
| 40 | spacex-81773-unsplash.jpg            |    1982 |     1133 |
| 41 | spacex-81773-unsplash.jpg            |     991 |      566 |
| 42 | spacex-81773-unsplash.jpg            |     100 |       67 |
| 43 | terence-burke-1417892-unsplash.jpg   |     500 |      400 |
| 44 | terence-burke-1417892-unsplash.jpg   |     640 |      366 |
| 45 | terence-burke-1417892-unsplash.jpg   |    1460 |      834 |
| 46 | terence-burke-1417892-unsplash.jpg   |    1982 |     1133 |
| 47 | terence-burke-1417892-unsplash.jpg   |     991 |      566 |
| 48 | terence-burke-1417892-unsplash.jpg   |      66 |      100 |

## Images with max size
The max size for each image.

| name                                 |   width |   height |
|:-------------------------------------|--------:|---------:|
| aditya-vyas-1392552-unsplash.jpg     |    3184 |     2123 |
| chuttersnap-255216-unsplash.png      |    2600 |      800 |
| donald-giannatti-671274-unsplash.jpg |    1982 |     1133 |
| nasa-43567-unsplash.jpg              |    1982 |     1133 |
| nasa-43569-unsplash.jpg              |    1982 |     1133 |
| nasa-89116-unsplash.jpg              |    1982 |     1133 |
| profile-default.jpg                  |     100 |      100 |
| spacex-1130896-unsplash.jpg          |     100 |       67 |
| spacex-81773-unsplash.jpg            |    1982 |     1133 |
| terence-burke-1417892-unsplash.jpg   |    1982 |     1133 |

The images were resized according to their max width (keeping proportion).

Note: this also revealed that `spacex-1130896-unsplash.jpg` is used in a `Media` entity but not referenced anywhere. We could probably remove this.

**Comment by arunz6161** [comment]
Lets remove spacex-1130896-unsplash.jpg. 
Does this cover #316 ?
Anything apart from the above 2 points before this is closed ?

**Comment by shadcn** [comment]
@arunz6161 Yes. I've added a new profile image (fixes #316).

**Review by cnovak — APPROVED** [review]
LGTM

**Pull request merged**
