### PR TITLE
Update NPM dependencies

### PR DESCRIPTION
**Pull request by jacine**

### CODE REVIEW

**Comment by kscheirer** [comment]
Can this cover https://github.com/apigee/apigee-devportal-kickstart-drupal/network/alert/themes/custom/apigee_kickstart/package-lock.json/lodash/open as well?

**Comment by jacine** [comment]
> Can this cover https://github.com/apigee/apigee-devportal-kickstart-drupal/network/alert/themes/custom/apigee_kickstart/package-lock.json/lodash/open as well?

Yes, this PR was opened to resolve that.  Merging it should fix.

**Comment by jacine** [comment]
And actually, I ran it again locally, and this time lodash did update.  🤷‍♀   Anyway, I'm getting the 0 of 0 now, so we should be good:

> fixed 0 of 0 vulnerabilities in 20595 scanned packages

**Review by kscheirer — APPROVED** [review]
👍 looks good!

**Pull request merged**
