### PR TITLE
[#435] Fix block related warnings when importing default content

### LINKED ISSUE #435: Block related warnings in watchdog after installing with Drupal 9
When installing Kickstart with Drupal 9, several block related warnings are seen in watchdog.This is not blocking installation or preventing functionality from getting installed.
 
Example:
image

## To Reproduce
1. Install latest Kickstart with Drupal 9, as described in https://github.com/apigee/devportal-kickstart-project-composer/pull/30
2. Enable demo content (not sure if this is related, though).
3. Upon installing, go to watchdog and see warnings.

## Screenshots
image

## Notes
This is not happening on Drupal 8 installations.

## Version Info
drupal/core: 9.0.7
apigee/apigee_devportal_kickstart: 8.x-1.21

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #435 

There's a change in Drupal 9 where: 

> Optional configuration provided by installed modules will be created before the install profile is installed. This change allows optional configuration in a profile's config/optional directory to depend on optional configuration provided by modules.

See the change record here: https://www.drupal.org/node/3118908 and related issue here: https://www.drupal.org/project/drupal/issues/3087130

So for `apigee_kickstart_content` we need to import the block config before the module is installed. I added a `hook_module_preinstall` hook to do this.

This fixes the warnings. However, `default_content.module` tries to re-import the content after `apigee_kickstart_content.module` is installed and fails with duplicate primary key errors because it is trying to import existing entities.

There is a fix for this https://www.drupal.org/project/default_content/issues/2698425 but only for the `2.x` branch. See comment https://www.drupal.org/project/default_content/issues/2698425#comment-13754294

I included a patch for `default_content 8.x-1.x` to fix this.

Let me know if this works

### CODE REVIEW

**Review by zakiya — APPROVED** [review]
Looks okay to me.

**Comment by arlina-espinoza** [comment]
@googlebot I consent.

**Comment by zakiya** [comment]
Sorry spoke too soon.  Tested with Drupal 9 and got the following errors on install:
2Installing_Apigee_Developer_Portal_Kickstart___Apigee_Developer_Portal_Kickstart
1Error___Apigee_Developer_Portal_Kickstart

The Drupal 8 install was fine.

**Comment by shadcn** [comment]
@zakiya hmm I can't reproduce this. Tested with Drupal 9.0.7, this PR and the `default_content` patch.

**Comment by arlina-espinoza** [comment]
@arshad I was testing this out, but when installing with composer I get the error:

```
Gathering patches for dependencies. This might take a minute.
  - Installing drupal/default_content (1.0.0-alpha9): Loading from cache
  - Applying patches for drupal/default_content
    patches/default-content-skip-existing.patch (Do not import existing entities)
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:234
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:234
   Could not apply patch! Skipping. The error was: The "patches/default-content-skip-existing.patch" file could not be downloaded: failed to open stream: No such file or directory
```

It looks like composer is looking for the patch in the "patches" dir relative to the composer root, not relative to the kickstart profile, so it's not found. Not sure we can hardcode the path either, because kickstart's directory might depend on the web root. Maybe reference the raw file here on github? 

**Update:** After referencing the patch here on github instead of a relative file it worked correctly with no errors shown or logged, both for D 8.9.7 and D 9.0.7. However, I referenced the file (https://raw.githubusercontent.com/apigee/apigee-devportal-kickstart-drupal/d20e26ccecf3034defcfa3ef97c32e9c5022f5ff/patches/default-content-skip-existing.patch) from the branch Arshad created. It worries me that it might disappear when we close this issue and delete the branch. Do you think we can host that patch on drupal.org? Or add the reference on github assuming it will be on the 1.x branch (https://raw.githubusercontent.com/apigee/apigee-devportal-kickstart-drupal/8.x-1.x/patches/default-content-skip-existing.patch)?

**Comment by shadcn** [comment]
I couldn't get it to work with a relative url either. I added the patch to the issue on d.o and updated composer.

**Comment by zakiya** [comment]
@arshad I hit the same error that was reported here: https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/394#issuecomment-715610481

**Comment by shadcn** [comment]
@zakiya can you send me the steps for testing this? I want to check if the patch is applied.

**Comment by zakiya** [comment]
@arshad Here are the instructions I followed:

```
project=MYPROJECT 

composer create-project apigee/devportal-kickstart-project:9.x-dev $project

cd ~/Sites/$project/web/profiles/contrib

rm -rf apigee_devportal_kickstart

git clone git@github.com:apigee/apigee-devportal-kickstart-drupal.git apigee_devportal_kickstart

cd apigee_devportal_kickstart

gh pr checkout 439

open -a phpstorm composer.json

open -a phpstorm ~/Sites/$project/composer.json

## -- If patches, copy patches from kickstart's composer to $project/composer.json and run composer install 

cd ~/Sites/$project

composer install 

mkdir ~/Sites/$project/private

open -a phpstorm ~/Sites/$project/web/sites/default/settings.php

## -- add private file path: $settings['file_private_path'] = '../private';

chmod -Rf 777 web/sites/default

## -- Create host on MAMP and connect to db

open http://$project.l/core/install.php

## -- Go through drupal installer. 

## -- enter database creds 

## -- Configure Edge

## -- Enter Site info

**Comment by shadcn** [comment]
@zakiya It looks like this is an unrelated issue. Can you skip the `Configure Edge` step and test again please?

**Comment by shadcn** [comment]
@zakiya I submitted a PR to fix the #394

**Review by arlina-espinoza — APPROVED** [review]
LGTM, tested against both D8 and D9. Thanks @arshad !

**Pull request merged**
