### PR TITLE
fix: Remove dependency on drupal/adminimal_admin_toolbar for D10 comp…

### PR DESCRIPTION
**Pull request by sleepingmonk**
…atibility.

### CODE REVIEW

**Comment by divya-intelli** [comment]
@sleepingmonk , please create a ticket with more description about this change.

**Comment by vpa24** [comment]
I think we should remove the dependency 'adminimal_admin_toolbar' module due to its support limitations, as it is only compatible with Drupal 8 and 9. Since Drupal 9 has reached its end of life, it would be prudent to explore alternatives. I recommend considering [Admin Toolbar](https://www.drupal.org/project/admin_toolbar) as a suitable replacement for 'adminimal_admin_toolbar' module.

**Comment by divya-intelli** [comment]
> I think we should remove the dependency 'adminimal_admin_toolbar' module due to its support limitations, as it is only compatible with Drupal 8 and 9. Since Drupal 9 has reached its end of life, it would be prudent to explore alternatives. I recommend considering [Admin Toolbar](https://www.drupal.org/project/admin_toolbar) as a suitable replacement for 'adminimal_admin_toolbar' module.

Hi @vpa24 ,  currently drupal/adminimal_admin_toolbar [dev](https://www.drupal.org/project/adminimal_admin_toolbar/releases/8.x-1.x-dev) version is compatible with Drupal 10 and is automatically downloaded without any error. Could you help us in understanding how it is affecting in your project.

**Comment by vpa24** [comment]
> > I think we should remove the dependency 'adminimal_admin_toolbar' module due to its support limitations, as it is only compatible with Drupal 8 and 9. Since Drupal 9 has reached its end of life, it would be prudent to explore alternatives. I recommend considering [Admin Toolbar](https://www.drupal.org/project/admin_toolbar) as a suitable replacement for 'adminimal_admin_toolbar' module.
> 
> Hi @vpa24 , currently drupal/adminimal_admin_toolbar [dev](https://www.drupal.org/project/adminimal_admin_toolbar/releases/8.x-1.x-dev) version is compatible with Drupal 10 and is automatically downloaded without any error. Could you help us in understanding how it is affecting in your project.

Hi @divya-intelli, I successfully upgraded from Drupal 9 to Drupal 10 without any issues but in my opinion, the [Admin Toolbar](https://www.drupal.org/project/admin_toolbar) module is better than the 'adminimal_admin_toolbar' module.

**Comment by sleepingmonk** [comment]
Thanks for the responses.

The package does not require the -dev version and so blocks a D10 upgrade.
Support for the adminimal_admin_toolbar module is not great.
I believe this adminimal_admin_toolbar is outdated given the current Drupal ecosystem.
I don't believe the apigee-devportal-kickstart package should be opinionated about which toolbar we should be using.

I will require the dev version in my base composer.json as a work around, but it is just a work around, this module will not be enabled.

**Review by divya-intelli — APPROVED** [review]
LGTM

**Comment by divya-intelli** [comment]
@sleepingmonk , thank you for the PR.

**Pull request merged**
