### PR TITLE
Utilize the Modernizr library from core

### PR DESCRIPTION
**Pull request by giteshk**
Fixed the js error on the analytics page because of a duplicate library.

### CODE REVIEW

**Review by shadcn — CHANGES_REQUESTED** [review]
Thanks. Some feedback: 

1. We also need to remove it from `src`: https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/8.x-1.x/themes/custom/apigee_kickstart/src/js/modernizr.js
2. Did you test it in IE11? We added this mainly to fix IE issues.

Thank you.

**Comment by giteshk** [comment]
@arshad I did delete the file.

Do you have any specific pages where the IE11 issues show up?

If you think you specifically need this file. Probably best to figure out how to replace the modernizr library in core to use this version.

**Comment by shadcn** [comment]
> @arshad I did delete the file.

There are 2 files. One under `src` and another one under `assets` :)

themes/custom/apigee_kickstart/src/js/modernizr.js
themes/custom/apigee_kickstart/assets/js/modernizr.js

> 
> Do you have any specific pages where the IE11 issues show up?

This was the issue we fixed https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/296

Just need to make sure this is not broken.

**Comment by shadcn** [comment]
@googlebot I consent.

**Comment by shadcn** [comment]
@giteshk I looked into this again today. So we can't really rely on core modernizr here since core does not have CSS grid support. 

I pushed some changes to replace core modernizr with our own version that has everything core has + CSS grid.

Tested and looks good on IE 11.

Thanks.

**Review by shadcn — APPROVED** [review]

**Pull request merged**
