### PR TITLE
changed the configuration name of title block breadcrumbs

### PR DESCRIPTION
**Pull request by vpa24**
In the **Radix** theme and this directory src/components/block/block.twig, they changed the configuration name of the block component from '_utility_classes_' to '_block_utility_classes_'. This code below is the comment part of that radix file:
```
{#
/**
 * @file
 * Template for a Block component.
 *
 * Available config:
 * - html_tag: The HTML tag for the block.
 * - block_utility_classes: An array of utility classes for block.
 */
#}
```

### CODE REVIEW

**Comment by shishir-intelli** [comment]
@vpa24 
Thank you for your contribution.
Google CLA is failing, please see https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/667/checks?check_run_id=18731790281 and sign the CLA.

We will review once the PR is ready.

**Comment by vpa24** [comment]
Thanks @shishir-intelli, I already signed the the CLA.

**Comment by shishir-intelli** [comment]
@vpa24 ,
The changes looks good, 

However, due to bootstrap 5 compatibility issue (see here https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/661) we have downgraded the radix version to 4  in the development branch (https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/662/files)

The above PR 667 changes can only be applied with radix 5, Team is working on Bootstrap 5 upgrades, once implemented we will approve and merge this PR.

**Review by divya-intelli — APPROVED** [review]
LGTM

**Pull request merged**
