### PR TITLE
[#83] Add migrations for Drupal 7 devportal entity types

### LINKED ISSUE #83: Migration from D7 Apigee developer portal
Curious if there is any migration path from the D7 distribution.

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #83 

This PR adds the `apigee_kickstart_migrate` module with migrations for all entity types that ship with the Drupal 7 devportal.

## Migrations

The following tables list the fields for all entity types that ship with the Drupal 7 Devportal and their direct mapping for Drupal 8 Kickstart. The apigee_kickstart_migrate module will include migrations for all entity types listed below.

  | Drupal 7 (Devportal) | Drupal 8 (Kickstart)
-- | -- | --
Content Types | **Article (article)** | **Article (article)**
  | title | title
  | body | body
  | field_keywords | field_tags
  | field_content_tag | field_tags
  |   |  
  | **Basic page (page)** | **Basic page (page)**
  | title | title
  | body | body
  |   |  
  | **FAQ (faq)** | **FAQ (faq)**
  | title | title
  | body | field_answer
  | field_detailed_question | -
  |   |  
  | **Forum topic (forum)** | **Forum topic (forum)**
  | title | title
  | body | body
  | taxonomy_forums | taxonomy_forums
  |   |  
Comment Types | **Comment (comment)** | **Comment (comment)**
  | author | author
  | subject | subject
  | comment_body | comment_body
  |   |  
Taxonomy | **Forums (forums)** | **Forum (forums)**
  | name | name
  |   |  
  | **Tags (tags)** | **Tags (tags)**
  | name | name

## Installation

1. Install the required migration modules: `composer require drupal/migrate_plus:^4.2 drupal/migrate_tools:^4.3`
2. Configure the source (d7) database connection in your `settings.php` or `settings.local.php` file.

```
$databases['migrate']['default'] = array (
  'database' => 'D7_DATABASE_NAME',
  'username' => 'USERNAME',
  'password' => 'PASSWORD',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
```
3. Enable the `apigee_kickstart_migrate` module: `drush en apigee_kickstart_migrate -y`
4. [Configure an Apigee Edge connection](https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge) and [run the developer sync](https://www.drupal.org/docs/8/modules/apigee-edge/synchronize-developers-with-apigee-edge). This is required to map user id fields.
5. You should now be ready to run the migrations.

#### To see a list of migrations, run the following command: 

`$ drush ms --group=devportal`

#### To run a migration:

`$ drush mim devportal_article --execute-dependencies` 

#### To revert a migration:

`$ drush mr devportal_article`

#### To run all devportal migrations:

`$ drush mim --group=devportal`

## Custom migrations

In most cases, the entity types on your Drupal 7 Devportal have been customized 
with additional fields. Since this is different for every Devportal, the 
default migrations do not handle these fields. You will need to write your 
own migration.

The **apigee_kickstart_migrate_example** module provides examples on how you 
can extend the default migrations to add your own custom fields.

### CODE REVIEW

**Comment by shadcn** [comment]
I added a README and an example module with documentation on how to extend the default migrations and add your own fields.

**Comment by nextagencyio** [comment]
Screen Shot 2019-10-07 at 11 27 18 AM

I was able to get this working following the instructions. I did some spot checking afterward and it looks good to me so far.

**Comment by minnur** [comment]
@googlebot I consent.

**Comment by minnur** [comment]
@cnovak @arunz6161 I tested migration and it worked as expected. One thing I noticed is the users/authors in forums are not getting migrated. Should we keep the users too? Currently it is migrating posts and setting users as Admin.

**Comment by shadcn** [comment]
@minnur the users are going to be pulled from Edge. Did you run the developer sync before running the migrations?

**Review by minnur — APPROVED** [review]
@arshad Ah got it, yeah I did not do that... It works as expected.

**Comment by jbennett13** [comment]
In progress.  Convo in other forums also mentioned this article, which may provide some context:  https://www.mediacurrent.com/blog/migrating-apigee-developer-portals-drupal-8

**Pull request merged**
