### PR TITLE
[DRUP-532] Forum Theming...

### PR DESCRIPTION
**Pull request by jacine**
And some other minor fixes related to buttons, title bar.

## Large

forum large

## Small

forum small

### CODE REVIEW

**Comment by jacine** [comment]
More screenshots...

## Forum index (large)

forum-index large

## Forum index (small)

forum-index small

## Forum (large)
forum-forum large

## Forum (small)
forum-forum small

**Comment by shadcn** [comment]
Looks really good. I'll pull and test.

Note: #58 adds a default user picture so this should fix the display here too.

**Review by shadcn — APPROVED** [review]
Tested on a new install. Everything looks good. Approved! Thanks @jacine

**Comment by jacine** [comment]
User photos too now, thanks @arshad! 

forum-images large

**Pull request merged**
