### PR TITLE
[#416] New endpoint to get credentials via Ajax calls.

### PR DESCRIPTION
**Pull request by minnur**
This one is related to this https://github.com/apigee/apigee-edge-drupal/pull/434

because show/hide credentials functionality altered in the kickstarter I had to make the change here as well.

### CODE REVIEW

**Comment by minnur** [comment]
Important: This should not be merged before this https://github.com/apigee/apigee-edge-drupal/pull/434

**Comment by arlina-espinoza** [comment]
@minnur Please see the comment about changes requested in https://github.com/apigee/apigee-edge-drupal/pull/434#pullrequestreview-446782138 to do access checking on the credentials endpoint. If implemented, this PR needs to be updated too.

**Comment by arlina-espinoza** [comment]
@googlebot I consent.

**Comment by arlina-espinoza** [comment]
Added bumping the required `apigee_edge` version to 8.x-1.13 because this should be merged and released after https://github.com/apigee/apigee-edge-drupal/pull/457 is released (on 8.x-1.13).

**Review by arlina-espinoza — APPROVED** [review]
LGTM, but holding off merging until apigee_edge 8.x-1.13 is released.

**Pull request merged**
