### PR TITLE
[#233] Feature parity for Monetization in Kickstart when enabled post site-install

### LINKED ISSUE #233: Add requirement module to allow easier setup if m10n is enabled after install
The end result of enabling Monetization in Kickstart is different depending on the way you install it:

- **Site install** (feature complete, highly recommended): Initial Apigee Kickstart installation, when performed in a browser, e.g. `https://localhost/core/install.php`, where Monetization features are configured as one of the installation steps.
  - Feature complete
  - Ability to configure your commerce store, pre-filled with Apigee organization details.
  - "Add credit" Product type, variant type, and variant created for you.
  - Supported in Edge currencies presented as options for you.
  - Products created based on those selected currencies, configured to work with "Add Credit" features out of the box.
  - Entity displays/fields for Product & Add Credit customizations/features.
  - Customizations to various Commerce module views.
  - Customizations to Apigee Monetization entity displays.
  - Custom theming support in Apigee Kickstart theme for the Entity Displays & Commerce views overrides.

- **Module install**: Apigee Kickstart Portal is already installed, and *Apigee Kickstart Monetization* module is enabled on `/admin/modules`.
  - "Add credit" Product type, variant type, and variant created for you.
  - Entity displays/fields for Product & Add Credit customizations/features.
  - Custom theming support (not as complete as site-install?).  Looking to improve this in #232.

The reason for this is simply because of features available in Drupal, and one being designed to be interactive and one not.  When installing the profile, you have the ability to create installation steps (tasks) and offer configuration options, accept user input, and evaluate and act on it.  When enabling a module, you don't have any of that.

Because of the way Monetization features are typically handled at Apigee, as an Edge add-on, it's common for Monetization to be added at a later date.   At this point, if the a portal has already been installed, then the *module-install* is the only option, and it's less feature complete.

It would be great if we could find a way to achieve the same end result, whether enabled at time of installation or after a portal installation already exists.

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #233.

This is WIP

### CODE REVIEW

**Comment by arlina-espinoza** [comment]
@arshad This is really great! :clap: :clap: :clap:  As we talked about, it would be ideal for these checks to be moved to the `apigee_m10n_add_credit` module, so I've done the following:

- Moved the profile requirements module to contrib as [_requirements_](https://www.drupal.org/project/requirements-0).
- Pushed an update to your branch that uses that module.

I'm working on a PR to `apigee_m10n_add_credit` that uses this module, and moves some of these requirements, when that is done I'll push an update to remove them from this PR.

**Comment by arlina-espinoza** [comment]
@arshad I've pushed the requirements module to contrib:

- Github repo: https://github.com/arlina-espinoza/drupal-requirement
- Drupal module: https://www.drupal.org/project/requirement

I've pushed updates to this PR to use it and also added requirements groups. What is left to do is move some of these requirements to the `apigee_m10n_add_credit` module and leave the other stuff here. :+1:

**Comment by cnovak** [comment]
@arlina-espinoza & @arshad have signed CLAs

**Comment by arlina-espinoza** [comment]
Moved applicable requirements to the add credit module, and left here enhancements - corresponding PR on the other module is: https://github.com/apigee/apigee-m10n-drupal/pull/191

**Comment by shadcn** [comment]
Just need the cla and we are good to go here.

**Review by arlina-espinoza — APPROVED** [review]
Thanks @arshad . Just waiting on feedback from @cnovak regarding adding the requirement module dependency on both this PR and [apigee-m10n-drupal #190](https://github.com/apigee/apigee-m10n-drupal/pull/191).

**Comment by shadcn** [comment]
This has been moved to the contrib modules. See apigee/apigee-m10n-drupal#190

**Pull request closed without merging**
