### PR TITLE
API Docs Configuration

### PR DESCRIPTION
**Pull request by jacine**
This is a screenshot:

Screen Shot 2019-03-20 at 12 56 42 PM

### CODE REVIEW

**Comment by jacine** [comment]
Ok, this is rebased, and should be ready.

**Comment by Jaesin** [comment]
This is for [DRUP-530].

Theming for this will happen later so the look is obviously pending.

There should be a way to get to the API Doc from the listing card and none of the elements are configured to link to the entity. Is this because the linking is going to happen in a template with addition of the "View Documentation" card footer?

**Comment by jacine** [comment]
> Theming for this will happen later so the look is obviously pending.

This PR is about configuration.  As theming has just started today, the current state of the *entire* kickstarter lacks any custom theming.  If this is a concern, maybe it should be noted in the README?   I don't think it is, because we're working in a feature branch, but that's an option.

> There should be a way to get to the API Doc from the listing card and none of the elements are configured to link to the entity. Is this because the linking is going to happen in a template with addition of the "View Documentation" card footer?

As noted in the configuration, this is rendering a card view mode of the entity.  This is what Radix outputs by default, which lacks a title/link.  When it comes time to theme this, of course, this will be addressed.

**Comment by Jaesin** [comment]
OK Great,

The other thing that is missing from API Docs as far as I see it is field configuration of the API Docs canonical page.

I talked to cnovak and he said we can use the [Swagger UI Field Formatter](https://www.drupal.org/project/swagger_ui_formatter) to render API Docs on the docs canonical URL.

I'm assuming there will be other field config as well. Just let us know if this will be handled in a followup PR and this one can be approved.

**Comment by jacine** [comment]
As I mentioned in DRUP-530, this will need to be assigned to someone else.  Nothing further is happening here right now. If that needs to block this PR, I can import this config, and still work on the theming locally. Whatever you would like to do is fine.

FYI: I'll be focusing on theming from here on out.

Thanks! :)

**Review by Jaesin — APPROVED** [review]
Functionally, there are 2 things missing.

1. A way to get to the API Doc from the card.

  This will be handled on the theme side so won't be a part of this PR.

2. A renderer for API Docs.

This is just a matter of configuration but will also require a library is added. The [Swagger UI Field Formatter](https://www.drupal.org/project/swagger_ui_formatter) should be used to render API Docs on the docs canonical URL.

**Pull request merged**
