### PR TITLE
Add sidebar regions to the theme

### PR DESCRIPTION
**Pull request by jacine**
Implement sidebars in #121.

### CODE REVIEW

**Review by shadcn — APPROVED** [review]
These look great. Tested on a few pages and on mobile. I like that you made these into components. This makes it easy for the themer. Approved! 👍

**Comment by jacine** [comment]
Here's a bunch of screenshots of what this does.  It's too big to upload: https://drive.google.com/open?id=1jPoXfJ2-T8Ybnss96EgEnkUmKaFNjVeS

**Review by shadcn — APPROVED** [review]
Ran these tests again. Everything looking great. Thanks for the awesome documentation @jacine. LGTM.

**Comment by jacine** [comment]
Thanks @arshad!

**Pull request merged**
