### PR TITLE
[#291] Update to the latest pathauto for 8.8.0 compatibility

### PR DESCRIPTION
**Pull request by shadcn**
WIP for #291

### CODE REVIEW

**Comment by shadcn** [comment]
We should probably wait on https://github.com/apigee/apigee-edge-drupal/pull/305 before we release this.

**Review by cnovak — CHANGES_REQUESTED** [review]
In the [Drupal core 8.8.0 release notes](https://www.drupal.org/project/drupal/releases/8.8.0) under the section **Changes to path aliases and a critical note for sites using the Pathauto contributed module**, it says:

>If you have the contributed Pathauto module enabled, you must update to the latest version of Pathauto before you update to Drupal 8.8.0. Failure to update Pathauto before updating core could result in data loss. Drupal 8.8.0 declares a conflict with Pathauto 8.x-1.5 or lower for this reason.

This makes me think we need to put out a release allowing users to upgrade to 8.8.0, and in a separate release put in this change along with release notes and instructions on how to:
1. Upgrade pathauto to latest
2. Run updb
2. Use Composer to upgrade to the Kickstart version w/Drupal core 8.8.0

Can we force this through code somehow by making sure users follow this process?

**Comment by shadcn** [comment]
@cnovak What if we do this in two steps. (Drupal 8.8.0 is not a security release so we could probably wait on this.)

**Step 1**
We release _Kickstart 8.x-1.8_ with the apps page update (which we should get out soon). We also add the pathauto update to it and implement a hook_requirement to check pathauto version and let users know that they should update to pathauto 1.6 (this pathauto version is compatible with both Drupal 8.7.x and 8.8.x)

This gives our users a chance to update pathauto before Drupal 8.8.x and on our end this gives us more time to sync the upgrade to Drupal 8.8.x across edge, m10n..etc.

**Step 2**
We then release _Kickstart 8.x-1.9_ with Drupal 8.8.x with more confidence that most installs have a compatible pathauto.

**Comment by arlina-espinoza** [comment]
> @cnovak What if we do this in two steps. (Drupal 8.8.0 is not a security release so we could probably wait on this.)
> 
> **Step 1**
> We release _Kickstart 8.x-1.8_ with the apps page update (which we should get out soon). We also add the pathauto update to it and implement a hook_requirement to check pathauto version and let users know that they should update to pathauto 1.6 (this pathauto version is compatible with both Drupal 8.7.x and 8.8.x)
> 
> This gives our users a chance to update pathauto before Drupal 8.8.x and on our end this gives us more time to sync the upgrade to Drupal 8.8.x across edge, m10n..etc.
> 
> **Step 2**
> We then release _Kickstart 8.x-1.9_ with Drupal 8.8.x with more confidence that most installs have a compatible pathauto.

@arshad This sounds great, let's ge ahead with this plan.

**Review by cnovak — APPROVED** [review]
Change and plan LGTM

**Comment by shadcn** [comment]
@arlina-espinoza @cnovak I added the Pathauto compatibility check.

Requirements_problem___Apigee_Developer_Portal_Kickstart

**Review by cnovak — COMMENTED** [review]
If I have pathauto 1.5 installed, I cannot install this PR since the composer.json will not allow it, so looks good. I did not test the `apigee_devportal_kickstart_requirements`. It makes sense, but how can you end up hitting the code in `apigee_devportal_kickstart_requirements`?

**Comment by shadcn** [comment]
@cnovak It runs during install, update and runtime. So if you're updating to the latest kickstart, it will prompt you to update pathauto as well. It also display a message on the status report page.

**Review by arlina-espinoza — APPROVED** [review]
LGTM. Thanks @arshad :)

**Comment by cnovak** [comment]
Just trying to think of how the `apigee_devportal_kickstart_requirements` message would dispplayed @arshad. You need to use Composer to install/update, I don't think there is a way a user would end up seeing the `apigee_devportal_kickstart_requirements` message unless they manually downloaded and replaced the version of pathauto w/a version < 1.5, due to the "conflict" section in composer.json.  Let me know if there is a path I did not think of.

**Comment by arlina-espinoza** [comment]
@cnovak It could be in case the user did an update of kickstart manually, without using composer, which isn't recommended or supported, but it could happen.

**Pull request merged**
